### ISSUE TITLE
Flutter 项目中锁定 LTS 版本为 mmkv: 1.3.9 无效

### ISSUE THREAD

**Issue by naivetoby** [Tencent/MMKV#1410]
亲爱的 mmkv 开发团队，

感谢你们为开源社区做出的贡献！作为一名使用 mmkv Flutter 插件的开发者，我注意到在 1.3.9 版本的 pubspec.yaml 文件中，以下依赖没有被锁定：

```yaml
mmkv_ios:
  ^1.0.5
mmkv_android:
  ^1.0.5
mmkv_ohos:
  ^1.0.1
```

这意味着，当新的 flutter mmkv 2.0.0 发布后，用户的项目可能会在不知情的情况下自动升级这些插件，造成潜在的破坏性更新（特别是 Android 不再支持 32 位平台）。我建议发布一个新的 1.3.x  LTS 版本，锁定这些插件的依赖，或者将它们的插件版本更新为 2.0.x，以避免这种情况。这样一来，1.3.x 的 LTS 特性将得以保持。

再次感谢你们的努力，期待你们的回复！
