### ISSUE TITLE
MMKV.clearAll causes crash in Android.

### ISSUE THREAD

**Issue by wkable** [Tencent/MMKV#814]
MMKV Logs:
```
╔════════════════════════════════════════════════════════════════════════════════╟────────────────────────────────────────────────────────────────────────────────────────
║ MMKV.encodeString  (MMKV.java:-2)
║    MMKV.mmkvLogImp  (MMKV.java:815)
║       KLogMMKVHandler.mmkvLog  (KLogMMKVHandler.kt:28)
╟────────────────────────────────────────────────────────────────────────────────────────
║ ###<MMKV_IO.cpp:346::ensureMemorySize>[permanent_data] file not valid
╚════════════════════════════════════════════════════════════════════════════════════════
╔════════════════════════════════════════════════════════════════════════════════╟────────────────────────────────────────────────────────────────────────────────────────
║ MMKV.clearAll  (MMKV.java:-2)
║    MMKV.mmkvLogImp  (MMKV.java:815)
║      MMKVHandler.mmkvLog  (KLogMMKVHandler.kt:27)
╟────────────────────────────────────────────────────────────────────────────────────────
║ ###<MMKV_IO.cpp:1047::clearAll>cleaning all key-values from [user_info_data]
╚════════════════════════════════════════════════════════════════════════════════════════
```

And crash stack:

```
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 Build fingerprint: 'Xiaomi/vangogh/vangogh:10/QKQ1.191222.002/V12.0.6.0.QJVCNXM:user/release-keys'
 Revision: '0'
 ABI: 'arm'
 Timestamp: 2022-01-06 18:53:40+0800
 uid: 10351
 signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
 Cause: null pointer dereference
     r0  00000000  r1  00000000  r2  00000000  r3  bd634edc
     r4  d664a620  r5  00000000  r6  00000000  r7  bd634ec0
     r8  00000000  r9  d5862000  r10 bd634f20  r11 d5862000
     ip  87c73065  sp  bd634eb0  lr  c00dc027  pc  c00da13c
 backtrace:
       #02 pc 000dc519  /apex/com.android.runtime/lib/libart.so (art_quick_generic_jni_trampoline+40) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #03 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #04 pc 0043c93d  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+248) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #05 pc 000dff81  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+168) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #06 pc 00214663  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+270) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #07 pc 00210857  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+738) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #08 pc 00431caf  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+594) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #09 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #11 pc 00431f27  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #12 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #13 pc 00008f82  [anon:dalvik-classes16.dex extracted in memory from /data/app/com.xxx.xxx-mopTxL23Hc_tmzOk5jIVxA==/base.apk!classes16.dex] 
       #14 pc 00431f27  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #15 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #16 pc 00003824  [anon:dalvik-classes21.dex extracted in memory from /data/app/com.xxx.xxx-mopTxL23Hc_tmzOk5jIVxA==/base.apk!classes21.dex] 
       #17 pc 00431f27  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #18 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #20 pc 0043342d  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1536) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #21 pc 000d2a14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #23 pc 0043342d  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1536) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #24 pc 000d2a14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #26 pc 00431f27  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #27 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #29 pc 00431f27  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #30 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #32 pc 0043342d  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1536) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #33 pc 000d2a14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #34 pc 001f8182  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor.runWorker+158)
       #35 pc 00431f27  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #36 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #37 pc 001f6f30  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor$Worker.run+4)
       #38 pc 0043342d  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1536) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #39 pc 000d2a14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #40 pc 000ea988  /apex/com.android.runtime/javalib/core-oj.jar (java.lang.Thread.run+8)
       #41 pc 001f067f  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.3851647361611683220+166) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #42 pc 001f5093  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+122) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #43 pc 00426397  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+866) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #44 pc 000dc5a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #45 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #46 pc 0043c93d  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+248) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #47 pc 000dff81  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+168) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #48 pc 0037cd07  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #49 pc 0037da9b  /apex/com.android.runtime/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+302) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #50 pc 003af6ff  /apex/com.android.runtime/lib/libart.so (art::Thread::CreateCallback(void*)+1018) (BuildId: c27d1b7f6d511645d4ce711b85db4ad6)
       #51 pc 000ac4ed  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20) (BuildId: dcf0e174e93e33d22f35a631ba9c0de5)
       #52 pc 00062989  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: dcf0e174e93e33d22f35a631ba9c0de5)
```
